[server]
maxUploadSize = 20
enableXsrfProtection = true
enableCORS = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#087E8B"
backgroundColor = "#F5F8FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#172B3A"
font = "sans serif"
